development:
  adapter: postgresql
  encoding: unicode
  database: my_notes_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: my_notes_test
  pool: 5

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 5 %>